<a href="https://colab.research.google.com/github/kushantp58/Neural-Nets-Repo/blob/master/Playing_with_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# building basic functions with numpy
#1 . sigmoid function using np.exp(), 
#sigmoid(x) also known as logistic function which is more of a non linear function used not in ML but also in DL
import math
def basic_sigmoid(x):
  """
  compute sigmoid of x.

  Argument:
  x -- A scalar

  Return:
  s -- Sigmoid(x)
  """
  s = 1/(1 + math.exp(-x))
  return s

In [10]:
basic_sigmoid(3)

0.9525741268224334

In [12]:
## to explain why we don't use math.exp(x) in dl is because the inputs of the functions are real numbers 
## and here we use matrices and vectos which is why numpy is essential
x = [1,2,3]
# basic_sigmoid(x) -- uncomment to see the demo
import numpy as np
x = np.array([1,2,3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [17]:
def sigmoid(x):
  """
  compute sigmoid of x.

  Argument:
  x -- A scalar

  Return:
  s -- Sigmoid(x)
  """
  s = 1 / (1 + np.exp(-x))
  return s


In [18]:
x = np.array([1, 2, 3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

In [19]:
## Sigmoid gradient
## base function for further calculation of backpropagation
## sigmoid derivative(x) = sigma'(x)(1-sigma(x))
def sigmoid_Derivative(x):
  """
  Compute The gradient or slope of the derivative of the sigmoid function wrt to its input x.
  you can store the output of the sigmoid function into variables and then use it to calculate the gradient.

  Arguments:
  x -- A Scalar or numpy array

  Return
  ds -- Computed gradient
  """
  s = sigmoid(x)
  ds = s * (1-s)
  return ds

In [20]:
x = np.array([1, 2, 3])
sigmoid_Derivative(x)

array([0.19661193, 0.10499359, 0.04517666])

In [25]:
## Reshaping Arrays
## Always use in conjunction (shape,reshape) shape for getting ddimension of matix and reshape for reshaping x into some other dimension
def image2vector(image):
  """
  Argument:
   image -- a numpy array of shape (length,height,depth)

  Returns:
   v -- a vecotr of shape (lhb,1)
  """
  v = image
  v = v.reshape((v.shape[0]*v.shape[1],v.shape[2]))
  return v

In [26]:
# This is a 3 by 3 by 2 array, typically images will be (num_px_x, num_px_y,3) where 3 represents the RGB values
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print ("image2vector(image) = " + str(image2vector(image)))

image2vector(image) = [[0.67826139 0.29380381]
 [0.90714982 0.52835647]
 [0.4215251  0.45017551]
 [0.92814219 0.96677647]
 [0.85304703 0.52351845]
 [0.19981397 0.27417313]
 [0.60659855 0.00533165]
 [0.10820313 0.49978937]
 [0.34144279 0.94630077]]


In [40]:
### Normalizing rows is an important  technique used in ml and dl for normalization of data
### it often leads to a better performance coz gradient descent converges faster after normalization
### Dividing each vector by it's norm

def normalizeRows(x):
  """
  Implementation of a function which normalizes row of a matrix x to have unit length

  Argument:
  x -- A numpy matrix of shape (n,m)

  Returns:
  x -- The normalized row numpy matrix

 """
  x_norm = np.linalg.norm(x,axis = 1,keepdims=True)
  x = x / x_norm
  return x

In [41]:
x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
print("normalizeRows(x) = " + str(normalizeRows(x)))

normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


In [70]:
### Broadcasting function - which is useful for performing mathematical operations b/w arrays of different shapes
### softmax function using numpy which is a normalizing function when algorithm needs to classify two or more classes
def softmax(x):
  """
  Calculates the softmax for each row of the input row vector x .

  Argument:
  x  -- A numpy matrix of shape(m,n)

  Returns:
  s -- A numpy matric equal to softmax 
  
  """
  x_exp = np.exp(x)
  x_sum = np.sum(x_exp,axis = 1,keepdims = True)
  s = x_exp / x_sum
  return s

In [71]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(x)))

softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


In [74]:
## Vectorization - Demo of difference between Classic and vectorized computations
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i]*x2[i]
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC OUTER PRODUCT IMPLEMENTATION ###
tic = time.process_time()
outer = np.zeros((len(x1),len(x2))) # we create a len(x1)*len(x2) matrix with only zeros
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i]*x2[j]
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j]*x1[j]
toc = time.process_time()
print ("gdot = " + str(gdot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 278
 ----- Computation time = 0.07428400000009105ms
outer = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0

In [75]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print ("gdot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 278
 ----- Computation time = 0.09580900000116799ms
outer = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
 ----- Computation time = 0.09442600000042489ms
elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 ----- Computation time = 0.10237899999943068ms
gdot = [24.33371835 22.39790943 29.631188

In [77]:
## the vectorized implementation is much cleaner and more efficient. For bigger vectors/matrices, the differences in running time become even bigger. 
## Implementations of L1 and L2 functions
## L1 loss  - used for evaluation of the performance of the model , bigger the loss , more efficient are your predictions of your values from your true values
## convex optimizations like GD are used for training ur model and minimizing cost

def L1(yhat,y):
  """
  Arguments:
  yhat - predicted labels of size m
  y -- vector of size m

  Returns:
  loss - the value of L1 loss functions defined

  """
  loss = np.sum(abs(yhat - y))
  return loss

In [78]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

L1 = 1.1


In [83]:
## next is l2 loss which is second norm of l1
def L2(yhat,y):
  loss =  np.dot(y - yhat,y - yhat)
  return loss

In [84]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(yhat,y)))

L2 = 0.43


 What to remember:


    np.exp(x) works for any np.array x and applies the exponential function to every coordinate
    the sigmoid function and its gradient
    image2vector is commonly used in deep learning
    np.reshape is widely used. In the future, you'll see that keeping your matrix/vector dimensions straight will go toward eliminating a lot of bugs.
    numpy has efficient built-in functions
    broadcasting is extremely useful

    Vectorization is very important in deep learning. It provides computational efficiency and clarity.
    reviewed the L1 and L2 loss.
    familiar with many numpy functions such as np.sum, np.dot, np.multiply, np.maximum, etc...
